domd: fix PVRUM postinstall script failure
During do_rootfs command following message was shown:
ERROR: Postinstall scriptlets of ['gles-user-module'] have failed.
If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.

Previously post-installation script`s return code 0 was treated
as warning. Since Yocto-thud lib/oe/package_manager.py turns
pos-tinstallation failure warnings into bitbake failures.
The reason of failure - variable INITSCRIPT_NAME is wrong.
Post-installation script was trying to set run-level for non
existing file, so fix it.

Signed-off-by: Iurii Artemenko <iurii_artemenko@epam.com>
Reviewed-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>